name: flutter_qr_bar_scanner_example
description: Demonstrates how to use the flutter_qr_bar_scanner plugin.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  url_launcher: ^5.7.5
  flutter_spinkit: ^4.1.2+1
  liquid_progress_indicator: ^0.3.2
  circular_countdown: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_qr_bar_scanner:
    path: ../

flutter:
  uses-material-design: true